name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: laggar-linux-amd64
          - os: windows-latest
            artifact: laggar-windows
          - os: macos-latest
            artifact: laggar-macos-amd64

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --release
    
    - name: Run tests
      run: cargo test --verbose
    
    - uses: actions/checkout@v2
    
    - run: mkdir -p target/release/

    - run: echo test > target/release/laggar.exe

    - uses: actions/upload-artifact@v2
      with:
        name: laggar-${{ matrix.artifact }}
        path: target/release/laggar.exe
    
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
